//! Rust self-check: assert the current build reproduces committed golden scores.
//!
//! This guards the validated Rust reference against regressions — e.g. an `ort`
//! upgrade that silently shifts logits.  If this test fails after a dependency
//! bump you must re-validate the model against Heimdall before regenerating the
//! golden vectors.
//!
//! # Running
//!
//! ```sh
//! SUSFACTOR_MODEL_DIR=/path/to/cache/susfactor-v1 \
//!   cargo test --test susfactor_parity --features susfactor --release
//! ```
//!
//! The test is skipped (not failed) if SUSFACTOR_MODEL_DIR is not set or the
//! model files are absent, so it never breaks a default offline `cargo test`.

#![cfg(feature = "susfactor")]

use odin_prompt_toolkit::providers::ModelCache;
use odin_prompt_toolkit::susfactor::SusFactorClassifier;

/// Maximum allowed absolute difference between the committed rust_score and the
/// current run.  This catches meaningful numeric drift while tolerating harmless
/// FP rounding (e.g. f32→f64 widening).  If the model or ORT changes the value
/// enough to exceed this bound, that is intentional signal — not noise to widen.
const TOLERANCE: f64 = 1e-4;

struct GoldenVector {
    name: &'static str,
    prompt: &'static str,
    rust_score: f64,
    expected_label: &'static str,
}

/// Committed golden vectors — generated by extract_susfactor_goldens and
/// reviewed before merging.  Update only via `make generate-susfactor-goldens`.
///
/// NOTE: rust_score values remain 0.0 until the extraction script has been run
/// and the fixture committed.  The test skips vectors whose committed score is
/// exactly 0.0 (sentinel for "not yet generated") so a fresh clone with no
/// model still passes.
fn goldens() -> Vec<GoldenVector> {
    // Read the fixture file at test time so the Rust test and the JSON fixture
    // stay in sync without manual duplication.
    let fixture_path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("..")
        .join("spec")
        .join("test-vectors")
        .join("susfactor_vectors.json");

    let raw = match std::fs::read_to_string(&fixture_path) {
        Ok(s) => s,
        Err(e) => {
            eprintln!("skipping: could not read fixture: {e}");
            return vec![];
        }
    };

    let doc: serde_json::Value = match serde_json::from_str(&raw) {
        Ok(v) => v,
        Err(e) => {
            panic!("fixture JSON is malformed: {e}");
        }
    };

    // We can't return references to temporaries, so we leak the strings.
    // This is acceptable in a test binary that runs briefly and exits.
    let vectors = doc["vectors"].as_array().expect("vectors array");
    vectors
        .iter()
        .filter_map(|v| {
            let name = v["name"].as_str()?;
            let prompt = v["prompt"].as_str()?;
            let rust_score = v["rust_score"].as_f64()?; // null → None → filtered
            let expected_label = v["expected_label"].as_str()?; // null → filtered
            Some(GoldenVector {
                name: Box::leak(name.to_string().into_boxed_str()),
                prompt: Box::leak(prompt.to_string().into_boxed_str()),
                rust_score,
                expected_label: Box::leak(expected_label.to_string().into_boxed_str()),
            })
        })
        .collect()
}

fn model_dir() -> Option<String> {
    let dir = std::env::var("SUSFACTOR_MODEL_DIR").ok()?;
    let base = std::path::Path::new(&dir);
    if base.join("onnx").join("model.onnx").exists()
        && base.join("onnx").join("model.onnx_data").exists()
        && base.join("tokenizer.json").exists()
    {
        Some(dir)
    } else {
        None
    }
}

#[tokio::test]
async fn rust_scores_match_committed_goldens() {
    let Some(dir) = model_dir() else {
        eprintln!("skipping susfactor_parity: SUSFACTOR_MODEL_DIR not set or model missing");
        return;
    };

    let entries = goldens();
    if entries.is_empty() {
        eprintln!("skipping susfactor_parity: no committed scores yet (run make generate-susfactor-goldens)");
        return;
    }

    let cache = ModelCache::new().expect("ModelCache::new");
    let clf = SusFactorClassifier::new(&cache, None, Some(dir), None)
        .await
        .expect("load classifier");

    let mut failures = 0usize;

    for entry in &entries {
        // classify() returns ChunkedSusFactorResult since PR #15.
        // rust_score records chunk[0].score for both single- and multi-chunk
        // prompts. Use is_suspicious (any-chunk gate) for the label check,
        // matching the Python and Go parity test logic.
        let chunked = clf.classify(entry.prompt).await.expect("classify");
        let chunk0 = &chunked.chunks[0];

        let score_diff = (chunk0.score as f64 - entry.rust_score).abs();
        let got_label = if chunked.is_suspicious { "suspicious" } else { "safe" };
        let label_ok = got_label == entry.expected_label;
        let score_ok = score_diff <= TOLERANCE;

        if label_ok && score_ok {
            println!(
                "  ✅  {}: score={:.6} (Δ={:.2e}) chunks={}",
                entry.name, chunk0.score, score_diff, chunked.chunks.len()
            );
        } else {
            failures += 1;
            eprintln!(
                "  ❌  {}: score={:.6} (committed={:.6}, Δ={:.2e} > tol={:.0e}) label={} (expected={}) chunks={}",
                entry.name,
                chunk0.score,
                entry.rust_score,
                score_diff,
                TOLERANCE,
                got_label,
                entry.expected_label,
                chunked.chunks.len(),
            );
        }
    }

    assert_eq!(
        failures, 0,
        "{failures} golden vector(s) failed. If this is after a dep bump, re-validate \
        against Heimdall before running `make generate-susfactor-goldens`."
    );
}
